name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - main
      - develop
    paths:
      - "entrypoint.sh"
      - "action.yml"
      - "Dockerfile"

jobs:
  bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: version-tag
        id: tag
        uses: de-marauder/github-tag-action@main
        env:
          VERBOSE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_API_TAGGING: false # uses git cli
          WITH_V: true
          PRERELEASE: true

      - name: automatic-release
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
          prerelease: false

      - name: version-tag-major
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          tag="$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1)"
          [[ "$tag" =~ ^(v?)([0-9]+) ]] # Capture the "v" prefix (if it exists) and the major version number
          prefix=${BASH_REMATCH[1]}
          major=${BASH_REMATCH[2]}

          # update major tag with the same prefix style as the original tag
          git tag -f "${prefix}${major}"
          git push -f origin "${prefix}${major}"
